language: python
python:
  - "2.7"

env:
  - CABALVER=1.18 GHCVER=7.8.3

virtualenv:
  system_site_packages: true

before_install:
 - travis_retry sudo apt-get update && sudo apt-get install -y build-essential
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - travis_retry sudo apt-get install -y python-setuptools libxml2 libxslt1-dev python-dev
 - travis_retry sudo apt-get install mercurial
 - travis_retry hg clone https://PinPinIre@bitbucket.org/PinPinIre/pml-bnfc
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - export PATH=$PATH:$PWD/pml-bnfc/xml:$PWD/spin

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ] || [ ${GHCVER%.*} = "7.10" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi
 - (travis_retry cd pml-bnfc/xml && make)
 - travis_retry mkdir -p spin && curl http://spinroot.com/spin/Bin/spin643_linux64.gz -o spin/spin.gz && gunzip spin/spin.gz && chmod +x spin/spin
 - pip install -r requirements.txt

script:
  - make build
  - ./test-suite/runner-translator.sh ./src/main/translator-xml/PMLToPromela.sh ./test-suite/translator-inputs
  - ./src/test/uitest/runtest.sh